version: "3.8"

services:
  mysqldb:
    container_name: mysqldb-con
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: employeedb
    networks:
      springboot-mysql-net:

  springboot-restful-microservices:
    container_name: springboot-restful-microservices
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    networks:
      springboot-mysql-net:
    restart: on-failure

networks:
  springboot-mysql-net:
